### ISSUE TITLE
Add ability to download through HttpClient

### ISSUE THREAD

**Issue by patrickklaeren** [NETWeasel/NETWeasel.Windows#2]
On the consuming end we should allow for  the ability to pass in a custom `HttpClient`, which will serve as the single instance downloading the target application - especially useful if custom headers/agent needs to be set.

Squirrel relies on `WebClient`, which we could use, but is old and fairly sure deprecated?

**Comment by Trinitek** [comment]
An optional `HttpClient` parameter sounds good.

Let's shy away from `WebClient`.  If people want an update provider that uses `WebClient`, they will be able to write their own with proposal #7.

**Comment by patrickklaeren** [comment]
Implemented
