### ISSUE TITLE
Allow for different update sources, including offline sources

### ISSUE THREAD

**Issue by Trinitek** [NETWeasel/NETWeasel.Windows#7]
Instead of having a hard dependency on an HTTP downloader, we should instead depend on an abstract update source provider.  The standard HTTP downloader that NetWeasel will ship with will extend from this, and this will also allow consumers to write their own providers to allow for other update sources, such as downloading over non-HTTP protocols or locally from disk.

**Comment by patrickklaeren** [comment]
I've tackled this with `IUpdateProvider`, also implemented `HostedXmlUpdateProvider`, which should be considered the default provider. Not sure if we should also ship a JSON provider by default.

Each provider is responsible for downloading/retrieving and implementing `IUpdateProvider`

Currently, we're looking at:
```cs
Task<UpdateMeta> CheckForUpdate();
Task<string> DownloadUpdate(IProgress<double> progress = default);
```
Where `DownloadUpdate` returns the path to the downloaded archive.

`Updater` has a dependency to `IUpdateProvider`.
